### ISSUE TITLE
Fix image media url retutning 404. 

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Univast#17]
- When the school logo is uploaded when the school is created, save the image on the server. 
- Return the school logo URL as a complete path in the form of "https://domain.com/images/<school_logo_name>
- Image should be accessible by its URL.

**Comment by aybruhm** [comment]
> * When the school logo is uploaded when the school is created, save the image on the server.
> * Return the school logo URL as a complete path in the form of "https://domain.com/images/<school_logo_name>
> * Image should be accessible by its URL.

Hey, man. I can not find an endpoint that adds a new school to the database. Do you need me to also work on that? Or, do I just need to work on the school logo upload endpoint?

**Comment by devgenix** [comment]
> > * When the school logo is uploaded when the school is created, save the image on the server.
> > * Return the school logo URL as a complete path in the form of "https://domain.com/images/<school_logo_name>
> > * Image should be accessible by its URL.
> 
> Hey, man. I can not find an endpoint that adds a new school to the database. Do you need me to also work on that? Or, do I just need to work on the school logo upload endpoint?

The database is updated through the admin site. We currently do not use an endpoint for that.

**Comment by aybruhm** [comment]
> > > * When the school logo is uploaded when the school is created, save the image on the server.
> > > * Return the school logo URL as a complete path in the form of "https://domain.com/images/<school_logo_name>
> > > * Image should be accessible by its URL.
> > 
> > 
> > Hey, man. I can not find an endpoint that adds a new school to the database. Do you need me to also work on that? Or, do I just need to work on the school logo upload endpoint?
> 
> The database is updated through the admin site. We currently do not use an endpoint for that.

Oh, noted then.
