### ISSUE TITLE
Media files not rendered in Production with Debug off.

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Univast#19]
Currently, whitenoise is set up to render media files in production but it isn't working.

**Comment by aybruhm** [comment]
> Currently, whitenoise is set up to render media files in production but it isn't working.

Alright, noted.

**Comment by aybruhm** [comment]
@devgenix Unfortunately, whitenoise does not support media files. It says: _"WhiteNoise is unsuitable for serving user-uploaded “media” files. It only checks for static files at startup, so files added after the app starts won’t be seen"_. See [here](https://whitenoise.readthedocs.io/en/stable/django.html#serving-media-files). 

Shall we opt for cloudinary?

**Comment by devgenix** [comment]
> @devgenix Unfortunately, whitenoise does not support media files. It says: _"WhiteNoise is unsuitable for serving user-uploaded “media” files. It only checks for static files at startup, so files added after the app starts won’t be seen"_. See [here](https://whitenoise.readthedocs.io/en/stable/django.html#serving-media-files).
> 
> Shall we opt for cloudinary?

Still got the Cloudinary info?

I previously thought about using Cloudinary but decided that since the media files we had to store were not going to be much, we could do with storing them on the server's local disk. 
So Whitenoise is used to serve static files as used [here](https://univast.faraday.africa/contribute) but not media files and especially not user-uploaded media files. Noted. 

Yes, let's go for Cloudinary. But remember that the media files are added when they are uploaded in the Admin site.

**Comment by aybruhm** [comment]
> > @devgenix Unfortunately, whitenoise does not support media files. It says: _"WhiteNoise is unsuitable for serving user-uploaded “media” files. It only checks for static files at startup, so files added after the app starts won’t be seen"_. See [here](https://whitenoise.readthedocs.io/en/stable/django.html#serving-media-files).
> > Shall we opt for cloudinary?
> 
> Still got the Cloudinary info?
> 
> I previously thought about using Cloudinary but decided that since the media files we had to store were not going to be much, we could do with storing them on the server's local disk. So Whitenoise is used to serve static files as used [here](https://univast.faraday.africa/contribute) but not media files and especially not user-uploaded media files. Noted.
> 
> Yes, let's go for Cloudinary. But remember that the media files are added when they are uploaded in the Admin site.

I don't. Can you send the credentials to me again? I'll appreciate.

**Comment by aybruhm** [comment]
> > @devgenix Unfortunately, whitenoise does not support media files. It says: _"WhiteNoise is unsuitable for serving user-uploaded “media” files. It only checks for static files at startup, so files added after the app starts won’t be seen"_. See [here](https://whitenoise.readthedocs.io/en/stable/django.html#serving-media-files).
> > Shall we opt for cloudinary?
> 
> Still got the Cloudinary info?
> 
> I previously thought about using Cloudinary but decided that since the media files we had to store were not going to be much, we could do with storing them on the server's local disk. So Whitenoise is used to serve static files as used [here](https://univast.faraday.africa/contribute) but not media files and especially not user-uploaded media files. Noted.
> 
> Yes, let's go for Cloudinary. But remember that the media files are added when they are uploaded in the Admin site.

 I understand. Cloudinary would actually be much better than saving to the server's local disk.

**Comment by devgenix** [comment]
> > > @devgenix Unfortunately, whitenoise does not support media files. It says: _"WhiteNoise is unsuitable for serving user-uploaded “media” files. It only checks for static files at startup, so files added after the app starts won’t be seen"_. See [here](https://whitenoise.readthedocs.io/en/stable/django.html#serving-media-files).
> > > Shall we opt for cloudinary?
> > 
> > 
> > Still got the Cloudinary info?
> > I previously thought about using Cloudinary but decided that since the media files we had to store were not going to be much, we could do with storing them on the server's local disk. So Whitenoise is used to serve static files as used [here](https://univast.faraday.africa/contribute) but not media files and especially not user-uploaded media files. Noted.
> > Yes, let's go for Cloudinary. But remember that the media files are added when they are uploaded in the Admin site.
> 
> I don't. Can you send the credentials to me again? I'll appreciate.

Check the workspace.
