### ISSUE TITLE
Add rate limiting by API keys to 50 requests/hour

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Univast#8]

**Comment by devgenix** [comment]
Is there a way to limit rates for a specific API Key?

Also, can an env var be used for the rate value?

@aybruhm

**Comment by aybruhm** [comment]
> Is there a way to limit rates for a specific API Key?
> 
> Also, can an env var be used for the rate value?
> 
> @aybruhm 

Yes, and yes.
